const KEY='zhimoji_web_v1';
const empty=()=>({pens:[],inks:[],papers:[],fills:[],paperUsages:[],tests:[]});
let db=load(); let state={tab:'home',search:'',view:null};
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return x&&typeof x==='object'?Object.assign(empty(),x):empty()}catch(e){return empty()}}
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function uid(p){return p+'_'+Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function fmt(s){return s?String(s).replace(/-/g,'/'):''}
function inkStatus(i){if(!i)return'active';if(i.statusManual==='empty')return'empty';if(i.statusManual==='active')return'active';const used=db.fills.filter(f=>f.inkId===i.id).reduce((a,f)=>a+(+f.ml||0),0);const remain=(+i.volume||0)-used-(+i.initialUsed||0);return (+i.volume||0)&&remain<=0?'empty':'active'}
function openFill(penId){return db.fills.find(f=>f.penId===penId&&!f.endDate)}
function inkName(id){const i=db.inks.find(x=>x.id===id);return i?(i.colorName||i.series||'未命名墨水'):'（已删除）'}
function penName(id){const p=db.pens.find(x=>x.id===id);return p?((p.brand||'')+' '+(p.model||'')).trim()||'未命名钢笔':'（已删除）'}
function swatch(i){if(!i)return'';const c1=i.colorHex||'#ccc',c2=i.colorHex2;if(i.gradientEnabled&&c2&&c2!==c1)return`linear-gradient(135deg,${c1},${c2})`;return c1}
function layout(content){document.getElementById('app').innerHTML=`<div class="wrap"><header class="top"><h1>纸墨记</h1><div class="sub">我的钢笔、墨水与纸张记录</div></header><main class="content">${content}</main><nav class="nav">${[['home','⌂','首页'],['pen','✒','钢笔'],['ink','●','墨水'],['paper','▤','纸张'],['me','☷','我的']].map(x=>`<button class="${state.tab===x[0]?'active':''}" onclick="go('${x[0]}')"><b>${x[1]}</b>${x[2]}</button>`).join('')}</nav></div>`}
function go(tab){state={tab,search:'',view:null};render()}
function render(){if(state.tab==='home')return home();if(state.tab==='pen')return listPage('pen','钢笔',db.pens,p=>((p.brand||'')+' '+(p.model||'')).trim()||'未命名钢笔');if(state.tab==='ink')return listPage('ink','墨水',db.inks,i=>i.colorName||i.series||'未命名墨水');if(state.tab==='paper')return listPage('paper','纸张',db.papers,p=>((p.brand||'')+' '+(p.name||'')).trim()||'未命名纸张');return me()}
function home(){const fills=db.fills.length,activePens=db.pens.filter(p=>p.status!=='idle'&&p.status!=='retired').length;layout(`<div class="grid"><div class="card"><div class="stat">${db.pens.length}</div><div class="label">钢笔</div></div><div class="card"><div class="stat">${db.inks.length}</div><div class="label">墨水</div></div><div class="card"><div class="stat">${db.papers.length}</div><div class="label">纸张</div></div><div class="card"><div class="stat">${fills}</div><div class="label">灌墨记录</div></div></div><div class="section-title">当前灌墨</div>${db.fills.filter(f=>!f.endDate).length?`<div class="list">${db.fills.filter(f=>!f.endDate).map(f=>`<div class="card row"><div class="swatch" style="background:${swatch(db.inks.find(i=>i.id===f.inkId))}"></div><div class="grow"><div class="name">${esc(penName(f.penId))}</div><div class="meta">${esc(inkName(f.inkId))} · ${esc(f.ml||'')} ml · ${fmt(f.date)}</div></div><button class="ghost" onclick="editFill('${f.id}')">编辑</button></div>`).join('')}</div>`:`<div class="card empty">还没有正在使用的墨水</div>`}`)}
function listPage(type,title,items,label){let q=state.search.toLowerCase();let arr=items.filter(x=>!q||JSON.stringify(x).toLowerCase().includes(q));layout(`<div class="bar"><input class="input" placeholder="搜索${title}" value="${esc(state.search)}" oninput="state.search=this.value;render()"><button class="primary" onclick="openForm('${type}')">＋</button></div><div class="list">${arr.length?arr.map(x=>itemCard(type,x,label)).join(''):`<div class="card empty">暂无${title}</div>`}</div>`)}
function itemCard(type,x,label){if(type==='ink')return`<div class="card row" onclick="openDetail('ink','${x.id}')"><div class="swatch" style="background:${swatch(x)}"></div><div class="grow"><div class="name">${esc(label(x))}</div><div class="meta">${esc([x.brand,x.series,x.volume?x.volume+' ml':'',inkStatus(x)==='empty'?'已空':''].filter(Boolean).join(' · '))}</div></div></div>`;return`<div class="card row" onclick="openDetail('${type}','${x.id}')"><div class="grow"><div class="name">${esc(label(x))}</div><div class="meta">${esc([x.nib,x.spec,x.location].filter(Boolean).join(' · '))}</div></div></div>`}
function openDetail(type,id){state.view={type,id};detail()}
function detail(){const {type,id}=state.view;const a=db[type==='pen'?'pens':type==='ink'?'inks':'papers'];const x=a.find(v=>v.id===id);if(!x)return go(type);let body='';if(type==='pen'){const f=openFill(id);body=`<div class="card"><div class="name">${esc((x.brand||'')+' '+(x.model||''))}</div><div class="meta">${esc([x.nib,x.nibMaterial,x.location].filter(Boolean).join(' · '))}</div>${f?`<div class="section-title">当前墨水</div><div class="row"><div class="swatch" style="background:${swatch(db.inks.find(i=>i.id===f.inkId))}"></div><div class="grow">${esc(inkName(f.inkId))}<div class="meta">${fmt(f.date)} · ${f.ml||''} ml</div></div></div>`:`<div class="meta" style="margin-top:14px">当前没有灌墨</div>`}</div><div class="actions"><button class="primary" onclick="openForm('fill',null,'${id}')">灌墨 / 换墨</button><button class="ghost" onclick="openForm('pen','${id}')">编辑</button></div><div class="section-title">灌墨历史</div><div class="list">${db.fills.filter(f=>f.penId===id).sort((a,b)=>(b.date||'').localeCompare(a.date||'')).map(f=>`<div class="card row"><div class="swatch" style="background:${swatch(db.inks.find(i=>i.id===f.inkId))}"></div><div class="grow"><div class="name">${esc(inkName(f.inkId))}</div><div class="meta">${fmt(f.date)} → ${fmt(f.endDate)||'现在'} · ${f.ml||''} ml</div></div></div>`).join('')}</div>`}else if(type==='ink'){const used=db.fills.filter(f=>f.inkId===id).reduce((a,f)=>a+(+f.ml||0),0),remain=(+x.volume||0)-used-(+x.initialUsed||0);body=`<div class="card"><div class="row"><div class="swatch" style="background:${swatch(x)}"></div><div><div class="name">${esc(x.colorName||x.series||'未命名墨水')}</div><div class="meta">${esc([x.brand,x.series].filter(Boolean).join(' · '))}</div></div></div><div class="section-title">使用情况</div><div class="meta">容量 ${x.volume||'—'} ml · 已记录使用 ${used} ml · 剩余约 ${Math.max(remain,0).toFixed(1)} ml</div></div><div class="actions"><button class="ghost" onclick="openForm('ink','${id}')">编辑</button></div>`}else body=`<div class="card"><div class="name">${esc((x.brand||'')+' '+(x.name||''))}</div><div class="meta">${esc([x.style,x.spec,x.weight?x.weight+' g':'',x.location].filter(Boolean).join(' · '))}</div><div class="section-title">数量</div><div class="meta">购入 ${x.buyQty||0} · 已用 ${x.usedQty||0} · 剩余 ${(x.buyQty||0)-(x.usedQty||0)}</div></div><div class="actions"><button class="ghost" onclick="openForm('paper','${id}')">编辑</button></div>`;layout(`<button class="back" onclick="go('${type}')">‹ 返回${type==='pen'?'钢笔':type==='ink'?'墨水':'纸张'}</button><h2>${type==='pen'?'钢笔详情':type==='ink'?'墨水详情':'纸张详情'}</h2>${body}`)}
function openForm(type,id='',presetPen=''){state.view={type:'form',formType:type,id:id||'',presetPen};form()}
function editFill(id){openForm('fill',id)}
function form(){const t=state.view.formType,id=state.view.id;let obj={};if(t==='pen')obj=db.pens.find(x=>x.id===id)||{};if(t==='ink')obj=db.inks.find(x=>x.id===id)||{};if(t==='paper')obj=db.papers.find(x=>x.id===id)||{};if(t==='fill')obj=db.fills.find(x=>x.id===id)||{penId:state.view.presetPen||'',inkId:db.inks.find(i=>inkStatus(i)!=='empty')?.id||'',date:today(),ml:'',endDate:'',note:''};const title=t==='pen'?'钢笔':t==='ink'?'墨水':t==='paper'?'纸张':'灌墨记录';let html='';if(t==='pen')html=`${field('品牌','brand',obj.brand)}${field('型号','model',obj.model)}${field('笔尖','nib',obj.nib)}${field('材质','nibMaterial',obj.nibMaterial)}${field('位置','location',obj.location)}${field('购买日期','buyDate',obj.buyDate,'date')}`;if(t==='ink')html=`${field('品牌','brand',obj.brand)}${field('系列','series',obj.series)}${field('颜色名','colorName',obj.colorName)}${field('色卡','colorHex',obj.colorHex||'#CFCFCF')}<div class="field"><label>容量（ml）</label><input class="input" name="volume" type="number" step="0.1" value="${esc(obj.volume||'')}"></div>${field('位置','location',obj.location)}`;if(t==='paper')html=`${field('品牌','brand',obj.brand)}${field('名称','name',obj.name)}${field('规格','spec',obj.spec)}${field('款式','style',obj.style)}${field('克重(g)','weight',obj.weight,'number')}${field('位置','location',obj.location)}`;if(t==='fill')html=`<div class="field"><label>钢笔</label><select class="select" name="penId">${db.pens.filter(p=>p.status!=='idle'&&p.status!=='retired').map(p=>`<option value="${p.id}" ${p.id===obj.penId?'selected':''}>${esc(penName(p.id))}</option>`).join('')}</select></div><div class="field"><label>墨水</label><select class="select" name="inkId">${db.inks.filter(i=>inkStatus(i)!=='empty').map(i=>`<option value="${i.id}" ${i.id===obj.inkId?'selected':''}>${esc(inkName(i.id))}</option>`).join('')}</select></div>${field('日期','date',obj.date,'date')}${field('灌墨量（ml）','ml',obj.ml,'number')}<div class="field"><label>结束日期（换墨时自动结束，也可手动填写）</label><input class="input" name="endDate" type="date" value="${esc(obj.endDate||'')}"></div>${field('备注','note',obj.note,'textarea')}`;layout(`<button class="back" onclick="state.view.id&&state.view.type!=='form'?detail():go('${t==='fill'?'pen':t}')">‹ 返回</button><div class="sheet-head"><h2>${id?'编辑':'新增'}${title}</h2></div><form class="form" onsubmit="submitForm(event)">${html}<div class="actions"><button class="primary" type="submit">保存</button><button class="ghost" type="button" onclick="go('${t==='fill'?'pen':t}')">取消</button></div>${id?`<button class="ghost danger" type="button" onclick="removeItem('${t}','${id}')">删除</button>`:''}</form>`)}
function field(label,name,value='',type='text'){if(type==='textarea')return`<div class="field"><label>${label}</label><textarea class="textarea" name="${name}">${esc(value)}</textarea></div>`;return`<div class="field"><label>${label}</label><input class="input" name="${name}" type="${type}" value="${esc(value)}"></div>`}
function submitForm(e){e.preventDefault();const t=state.view.formType,id=state.view.id;const fd=new FormData(e.target);const o=Object.fromEntries(fd.entries());if(t==='fill'){if(!o.penId||!o.inkId)return; if(id){const i=db.fills.findIndex(x=>x.id===id);db.fills[i]=Object.assign({},db.fills[i],o)}else{db.fills.forEach(f=>{if(f.penId===o.penId&&!f.endDate)f.endDate=o.date});db.fills.push(Object.assign({id:uid('fill'),createdAt:Date.now()},o))}}else{const arr=db[t==='pen'?'pens':t==='ink'?'inks':'papers'];if(id){const i=arr.findIndex(x=>x.id===id);arr[i]=Object.assign({},arr[i],o)}else arr.push(Object.assign({id:uid(t)},o))}save();go(t==='fill'?'pen':t)}
function removeItem(t,id){if(!confirm('确定删除吗？'))return;const key=t==='pen'?'pens':t==='ink'?'inks':t==='paper'?'papers':'fills';db[key]=db[key].filter(x=>x.id!==id);save();go(t==='fill'?'pen':t)}
function me(){layout(`<div class="card"><div class="name">本地数据</div><div class="meta">数据只保存在当前浏览器，不会自动上传到 GitHub。</div><div class="actions"><button class="primary" onclick="exportData()">导出备份</button><button class="ghost" onclick="document.getElementById('file').click()">导入备份</button></div><input id="file" type="file" accept="application/json,.json" style="display:none" onchange="importData(this.files[0])"></div><div class="section-title">统计</div><div class="grid"><div class="card"><div class="stat">${db.pens.length}</div><div class="label">钢笔</div></div><div class="card"><div class="stat">${db.inks.length}</div><div class="label">墨水</div></div><div class="card"><div class="stat">${db.papers.length}</div><div class="label">纸张</div></div><div class="card"><div class="stat">${db.fills.length}</div><div class="label">灌墨记录</div></div></div><div class="section-title">数据迁移</div><div class="card meta">这版 Web 会先使用自己的本地数据库。下一阶段会加入从你原微信小程序备份 JSON 直接导入，并保留你现有字段。</div>`)}
function exportData(){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='zhimoji-backup-'+today()+'.json';a.click();URL.revokeObjectURL(a.href)}
function importData(file){if(!file)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x||typeof x!=='object')throw 0;db=Object.assign(empty(),x);save();alert('导入成功');render()}catch(e){alert('备份文件无法识别')}};r.readAsText(file)}
render();
